version: '2'
services:
  web:
    build: .
    command: node --inspect=0.0.0.0:9229 server.js
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
      - "9229:9229"
