version: '2'
services:
  web:
    build: .
    command: node --inspect=5858 server.js 
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
      - "5858:5858"
